name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy Secret To application module
        run: |
          echo "PROJECT_API_KEY=$MAP_API_KEY" >> .env
        env:
          MAP_API_KEY: ${{ secrets.PROJECT_API_KEY }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy Secret To application module
        run: |
          echo "PROJECT_API_KEY=$MAP_API_KEY" >> .env
        env:
          MAP_API_KEY: ${{ secrets.PROJECT_API_KEY }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

      - name: Send Webhook Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "iOS Build Completed"}' \
          https://your-webhook-url.com

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy Secret To application module
        run: |
          echo "PROJECT_API_KEY=$MAP_API_KEY" >> .env
        env:
          MAP_API_KEY: ${{ secrets.PROJECT_API_KEY }}

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

      - name: Send Webhook Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Android Build Completed"}' \
          https://your-webhook-url.com
