name: flutter-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1.5.0
        with:
          channel: stable

      - run: flutter doctor -v

      - name: Get pub packages
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter unit tests
        run: flutter test
