name: CI
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Copy Secret To application module
        env:
          PROJECT_API_URL: ${{ secrets.PROJECT_API_URL}}				
          PROJECT_API_URL_DIR: config/.env	
          PROJECT_API_URL_TEST_DIR: config/.env
          PROJECT_API_URL_DIR_FILE_NAME: env.yml						
        run: echo $PROJECT_API_URL | base64 --decode > $PROJECT_API_URL_DIR/$PROJECT_API_URL_DIR_FILE_NAME && 	
              echo $PROJECT_API_URL | base64 --decode > $PROJECT_API_URL_TEST_DIR/$PROJECT_API_URL_DIR_FILE_NAME
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle