name: flutter-ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Clone Flutter repository with the latest stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter doctor -v

      - name: Get pub packages
        run: flutter pub get

      - name: Create .env file
        run: echo "API_KEY=${http://3.39.154.249}" > .env

      - name: Analyze code
        run: flutter analyze

      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Run Flutter unit tests
        run: flutter test
